### ISSUE TITLE
俺もテストしたいのでバグ報告するー

### ISSUE THREAD

**Issue by Akkey57492** [riyayaNetwork/riyayanetwork#2]
**バグを説明してください。**
Lobby鯖(/server lobby)のスポーン地点がおかしい。
よくわからない海にスポーンする。

**どうやって起きたんですか？**
参加しただけ。

**画像やスクリーンショットなどを添付してください**
ない。自分で確かめろ。

**環境**
 - OS: Windows10
 - Version 1.8.9

**この件について他に報告したいこと**
何もない。

**Comment by kinoko2k** [comment]
setspawn入れてないから

**Comment by riyaya1528** [comment]
RiyaAssistにsetSpawnのような機能を追加しました

**Comment by riyaya1528** [comment]
RiyaAssistにsetSpawnのような機能を追加しました
